
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const FieldType = {
  TEXT: 'TEXT',
  TEXTAREA: 'TEXTAREA',
  CHECKBOX: 'CHECKBOX',
  RADIO: 'RADIO',
  SINGLE_UPLOAD: 'SINGLE_UPLOAD',
  MULTI_UPLOAD: 'MULTI_UPLOAD',
  SINGLE_SELECT: 'SINGLE_SELECT',
  MULTI_SELECT: 'MULTI_SELECT'
} as const

export type FieldType = (typeof FieldType)[keyof typeof FieldType]


export const FieldComparator = {
  EQUALS: 'EQUALS',
  GREATER_THAN: 'GREATER_THAN',
  GREATER_OR_EQUALS_THAN: 'GREATER_OR_EQUALS_THAN',
  LESS_THAN: 'LESS_THAN',
  LESS_OR_EQUALS_THAN: 'LESS_OR_EQUALS_THAN'
} as const

export type FieldComparator = (typeof FieldComparator)[keyof typeof FieldComparator]
