
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FieldOption` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FieldOption
 * 
 */
export type FieldOptionModel = runtime.Types.Result.DefaultSelection<Prisma.$FieldOptionPayload>

export type AggregateFieldOption = {
  _count: FieldOptionCountAggregateOutputType | null
  _avg: FieldOptionAvgAggregateOutputType | null
  _sum: FieldOptionSumAggregateOutputType | null
  _min: FieldOptionMinAggregateOutputType | null
  _max: FieldOptionMaxAggregateOutputType | null
}

export type FieldOptionAvgAggregateOutputType = {
  order: number | null
}

export type FieldOptionSumAggregateOutputType = {
  order: number | null
}

export type FieldOptionMinAggregateOutputType = {
  id: string | null
  fieldId: string | null
  value: string | null
  label: string | null
  order: number | null
  active: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FieldOptionMaxAggregateOutputType = {
  id: string | null
  fieldId: string | null
  value: string | null
  label: string | null
  order: number | null
  active: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FieldOptionCountAggregateOutputType = {
  id: number
  fieldId: number
  value: number
  label: number
  order: number
  active: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type FieldOptionAvgAggregateInputType = {
  order?: true
}

export type FieldOptionSumAggregateInputType = {
  order?: true
}

export type FieldOptionMinAggregateInputType = {
  id?: true
  fieldId?: true
  value?: true
  label?: true
  order?: true
  active?: true
  createdAt?: true
  updatedAt?: true
}

export type FieldOptionMaxAggregateInputType = {
  id?: true
  fieldId?: true
  value?: true
  label?: true
  order?: true
  active?: true
  createdAt?: true
  updatedAt?: true
}

export type FieldOptionCountAggregateInputType = {
  id?: true
  fieldId?: true
  value?: true
  label?: true
  order?: true
  active?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type FieldOptionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FieldOption to aggregate.
   */
  where?: Prisma.FieldOptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FieldOptions to fetch.
   */
  orderBy?: Prisma.FieldOptionOrderByWithRelationInput | Prisma.FieldOptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FieldOptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FieldOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FieldOptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FieldOptions
  **/
  _count?: true | FieldOptionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FieldOptionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FieldOptionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FieldOptionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FieldOptionMaxAggregateInputType
}

export type GetFieldOptionAggregateType<T extends FieldOptionAggregateArgs> = {
      [P in keyof T & keyof AggregateFieldOption]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFieldOption[P]>
    : Prisma.GetScalarType<T[P], AggregateFieldOption[P]>
}




export type FieldOptionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FieldOptionWhereInput
  orderBy?: Prisma.FieldOptionOrderByWithAggregationInput | Prisma.FieldOptionOrderByWithAggregationInput[]
  by: Prisma.FieldOptionScalarFieldEnum[] | Prisma.FieldOptionScalarFieldEnum
  having?: Prisma.FieldOptionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FieldOptionCountAggregateInputType | true
  _avg?: FieldOptionAvgAggregateInputType
  _sum?: FieldOptionSumAggregateInputType
  _min?: FieldOptionMinAggregateInputType
  _max?: FieldOptionMaxAggregateInputType
}

export type FieldOptionGroupByOutputType = {
  id: string
  fieldId: string
  value: string
  label: string
  order: number
  active: boolean
  createdAt: Date
  updatedAt: Date
  _count: FieldOptionCountAggregateOutputType | null
  _avg: FieldOptionAvgAggregateOutputType | null
  _sum: FieldOptionSumAggregateOutputType | null
  _min: FieldOptionMinAggregateOutputType | null
  _max: FieldOptionMaxAggregateOutputType | null
}

type GetFieldOptionGroupByPayload<T extends FieldOptionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FieldOptionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FieldOptionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FieldOptionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FieldOptionGroupByOutputType[P]>
      }
    >
  >



export type FieldOptionWhereInput = {
  AND?: Prisma.FieldOptionWhereInput | Prisma.FieldOptionWhereInput[]
  OR?: Prisma.FieldOptionWhereInput[]
  NOT?: Prisma.FieldOptionWhereInput | Prisma.FieldOptionWhereInput[]
  id?: Prisma.StringFilter<"FieldOption"> | string
  fieldId?: Prisma.StringFilter<"FieldOption"> | string
  value?: Prisma.StringFilter<"FieldOption"> | string
  label?: Prisma.StringFilter<"FieldOption"> | string
  order?: Prisma.IntFilter<"FieldOption"> | number
  active?: Prisma.BoolFilter<"FieldOption"> | boolean
  createdAt?: Prisma.DateTimeFilter<"FieldOption"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FieldOption"> | Date | string
  field?: Prisma.XOR<Prisma.FieldScalarRelationFilter, Prisma.FieldWhereInput>
}

export type FieldOptionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
  value?: Prisma.SortOrder
  label?: Prisma.SortOrder
  order?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  field?: Prisma.FieldOrderByWithRelationInput
  _relevance?: Prisma.FieldOptionOrderByRelevanceInput
}

export type FieldOptionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  fieldId_value?: Prisma.FieldOptionFieldIdValueCompoundUniqueInput
  AND?: Prisma.FieldOptionWhereInput | Prisma.FieldOptionWhereInput[]
  OR?: Prisma.FieldOptionWhereInput[]
  NOT?: Prisma.FieldOptionWhereInput | Prisma.FieldOptionWhereInput[]
  fieldId?: Prisma.StringFilter<"FieldOption"> | string
  value?: Prisma.StringFilter<"FieldOption"> | string
  label?: Prisma.StringFilter<"FieldOption"> | string
  order?: Prisma.IntFilter<"FieldOption"> | number
  active?: Prisma.BoolFilter<"FieldOption"> | boolean
  createdAt?: Prisma.DateTimeFilter<"FieldOption"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FieldOption"> | Date | string
  field?: Prisma.XOR<Prisma.FieldScalarRelationFilter, Prisma.FieldWhereInput>
}, "id" | "fieldId_value">

export type FieldOptionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
  value?: Prisma.SortOrder
  label?: Prisma.SortOrder
  order?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.FieldOptionCountOrderByAggregateInput
  _avg?: Prisma.FieldOptionAvgOrderByAggregateInput
  _max?: Prisma.FieldOptionMaxOrderByAggregateInput
  _min?: Prisma.FieldOptionMinOrderByAggregateInput
  _sum?: Prisma.FieldOptionSumOrderByAggregateInput
}

export type FieldOptionScalarWhereWithAggregatesInput = {
  AND?: Prisma.FieldOptionScalarWhereWithAggregatesInput | Prisma.FieldOptionScalarWhereWithAggregatesInput[]
  OR?: Prisma.FieldOptionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FieldOptionScalarWhereWithAggregatesInput | Prisma.FieldOptionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FieldOption"> | string
  fieldId?: Prisma.StringWithAggregatesFilter<"FieldOption"> | string
  value?: Prisma.StringWithAggregatesFilter<"FieldOption"> | string
  label?: Prisma.StringWithAggregatesFilter<"FieldOption"> | string
  order?: Prisma.IntWithAggregatesFilter<"FieldOption"> | number
  active?: Prisma.BoolWithAggregatesFilter<"FieldOption"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"FieldOption"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"FieldOption"> | Date | string
}

export type FieldOptionCreateInput = {
  id?: string
  value: string
  label: string
  order?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  field: Prisma.FieldCreateNestedOneWithoutOptionsInput
}

export type FieldOptionUncheckedCreateInput = {
  id?: string
  fieldId: string
  value: string
  label: string
  order?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FieldOptionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  field?: Prisma.FieldUpdateOneRequiredWithoutOptionsNestedInput
}

export type FieldOptionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fieldId?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FieldOptionCreateManyInput = {
  id?: string
  fieldId: string
  value: string
  label: string
  order?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FieldOptionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FieldOptionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fieldId?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FieldOptionListRelationFilter = {
  every?: Prisma.FieldOptionWhereInput
  some?: Prisma.FieldOptionWhereInput
  none?: Prisma.FieldOptionWhereInput
}

export type FieldOptionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FieldOptionOrderByRelevanceInput = {
  fields: Prisma.FieldOptionOrderByRelevanceFieldEnum | Prisma.FieldOptionOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type FieldOptionFieldIdValueCompoundUniqueInput = {
  fieldId: string
  value: string
}

export type FieldOptionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
  value?: Prisma.SortOrder
  label?: Prisma.SortOrder
  order?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FieldOptionAvgOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type FieldOptionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
  value?: Prisma.SortOrder
  label?: Prisma.SortOrder
  order?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FieldOptionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
  value?: Prisma.SortOrder
  label?: Prisma.SortOrder
  order?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FieldOptionSumOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type FieldOptionCreateNestedManyWithoutFieldInput = {
  create?: Prisma.XOR<Prisma.FieldOptionCreateWithoutFieldInput, Prisma.FieldOptionUncheckedCreateWithoutFieldInput> | Prisma.FieldOptionCreateWithoutFieldInput[] | Prisma.FieldOptionUncheckedCreateWithoutFieldInput[]
  connectOrCreate?: Prisma.FieldOptionCreateOrConnectWithoutFieldInput | Prisma.FieldOptionCreateOrConnectWithoutFieldInput[]
  createMany?: Prisma.FieldOptionCreateManyFieldInputEnvelope
  connect?: Prisma.FieldOptionWhereUniqueInput | Prisma.FieldOptionWhereUniqueInput[]
}

export type FieldOptionUncheckedCreateNestedManyWithoutFieldInput = {
  create?: Prisma.XOR<Prisma.FieldOptionCreateWithoutFieldInput, Prisma.FieldOptionUncheckedCreateWithoutFieldInput> | Prisma.FieldOptionCreateWithoutFieldInput[] | Prisma.FieldOptionUncheckedCreateWithoutFieldInput[]
  connectOrCreate?: Prisma.FieldOptionCreateOrConnectWithoutFieldInput | Prisma.FieldOptionCreateOrConnectWithoutFieldInput[]
  createMany?: Prisma.FieldOptionCreateManyFieldInputEnvelope
  connect?: Prisma.FieldOptionWhereUniqueInput | Prisma.FieldOptionWhereUniqueInput[]
}

export type FieldOptionUpdateManyWithoutFieldNestedInput = {
  create?: Prisma.XOR<Prisma.FieldOptionCreateWithoutFieldInput, Prisma.FieldOptionUncheckedCreateWithoutFieldInput> | Prisma.FieldOptionCreateWithoutFieldInput[] | Prisma.FieldOptionUncheckedCreateWithoutFieldInput[]
  connectOrCreate?: Prisma.FieldOptionCreateOrConnectWithoutFieldInput | Prisma.FieldOptionCreateOrConnectWithoutFieldInput[]
  upsert?: Prisma.FieldOptionUpsertWithWhereUniqueWithoutFieldInput | Prisma.FieldOptionUpsertWithWhereUniqueWithoutFieldInput[]
  createMany?: Prisma.FieldOptionCreateManyFieldInputEnvelope
  set?: Prisma.FieldOptionWhereUniqueInput | Prisma.FieldOptionWhereUniqueInput[]
  disconnect?: Prisma.FieldOptionWhereUniqueInput | Prisma.FieldOptionWhereUniqueInput[]
  delete?: Prisma.FieldOptionWhereUniqueInput | Prisma.FieldOptionWhereUniqueInput[]
  connect?: Prisma.FieldOptionWhereUniqueInput | Prisma.FieldOptionWhereUniqueInput[]
  update?: Prisma.FieldOptionUpdateWithWhereUniqueWithoutFieldInput | Prisma.FieldOptionUpdateWithWhereUniqueWithoutFieldInput[]
  updateMany?: Prisma.FieldOptionUpdateManyWithWhereWithoutFieldInput | Prisma.FieldOptionUpdateManyWithWhereWithoutFieldInput[]
  deleteMany?: Prisma.FieldOptionScalarWhereInput | Prisma.FieldOptionScalarWhereInput[]
}

export type FieldOptionUncheckedUpdateManyWithoutFieldNestedInput = {
  create?: Prisma.XOR<Prisma.FieldOptionCreateWithoutFieldInput, Prisma.FieldOptionUncheckedCreateWithoutFieldInput> | Prisma.FieldOptionCreateWithoutFieldInput[] | Prisma.FieldOptionUncheckedCreateWithoutFieldInput[]
  connectOrCreate?: Prisma.FieldOptionCreateOrConnectWithoutFieldInput | Prisma.FieldOptionCreateOrConnectWithoutFieldInput[]
  upsert?: Prisma.FieldOptionUpsertWithWhereUniqueWithoutFieldInput | Prisma.FieldOptionUpsertWithWhereUniqueWithoutFieldInput[]
  createMany?: Prisma.FieldOptionCreateManyFieldInputEnvelope
  set?: Prisma.FieldOptionWhereUniqueInput | Prisma.FieldOptionWhereUniqueInput[]
  disconnect?: Prisma.FieldOptionWhereUniqueInput | Prisma.FieldOptionWhereUniqueInput[]
  delete?: Prisma.FieldOptionWhereUniqueInput | Prisma.FieldOptionWhereUniqueInput[]
  connect?: Prisma.FieldOptionWhereUniqueInput | Prisma.FieldOptionWhereUniqueInput[]
  update?: Prisma.FieldOptionUpdateWithWhereUniqueWithoutFieldInput | Prisma.FieldOptionUpdateWithWhereUniqueWithoutFieldInput[]
  updateMany?: Prisma.FieldOptionUpdateManyWithWhereWithoutFieldInput | Prisma.FieldOptionUpdateManyWithWhereWithoutFieldInput[]
  deleteMany?: Prisma.FieldOptionScalarWhereInput | Prisma.FieldOptionScalarWhereInput[]
}

export type FieldOptionCreateWithoutFieldInput = {
  id?: string
  value: string
  label: string
  order?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FieldOptionUncheckedCreateWithoutFieldInput = {
  id?: string
  value: string
  label: string
  order?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FieldOptionCreateOrConnectWithoutFieldInput = {
  where: Prisma.FieldOptionWhereUniqueInput
  create: Prisma.XOR<Prisma.FieldOptionCreateWithoutFieldInput, Prisma.FieldOptionUncheckedCreateWithoutFieldInput>
}

export type FieldOptionCreateManyFieldInputEnvelope = {
  data: Prisma.FieldOptionCreateManyFieldInput | Prisma.FieldOptionCreateManyFieldInput[]
  skipDuplicates?: boolean
}

export type FieldOptionUpsertWithWhereUniqueWithoutFieldInput = {
  where: Prisma.FieldOptionWhereUniqueInput
  update: Prisma.XOR<Prisma.FieldOptionUpdateWithoutFieldInput, Prisma.FieldOptionUncheckedUpdateWithoutFieldInput>
  create: Prisma.XOR<Prisma.FieldOptionCreateWithoutFieldInput, Prisma.FieldOptionUncheckedCreateWithoutFieldInput>
}

export type FieldOptionUpdateWithWhereUniqueWithoutFieldInput = {
  where: Prisma.FieldOptionWhereUniqueInput
  data: Prisma.XOR<Prisma.FieldOptionUpdateWithoutFieldInput, Prisma.FieldOptionUncheckedUpdateWithoutFieldInput>
}

export type FieldOptionUpdateManyWithWhereWithoutFieldInput = {
  where: Prisma.FieldOptionScalarWhereInput
  data: Prisma.XOR<Prisma.FieldOptionUpdateManyMutationInput, Prisma.FieldOptionUncheckedUpdateManyWithoutFieldInput>
}

export type FieldOptionScalarWhereInput = {
  AND?: Prisma.FieldOptionScalarWhereInput | Prisma.FieldOptionScalarWhereInput[]
  OR?: Prisma.FieldOptionScalarWhereInput[]
  NOT?: Prisma.FieldOptionScalarWhereInput | Prisma.FieldOptionScalarWhereInput[]
  id?: Prisma.StringFilter<"FieldOption"> | string
  fieldId?: Prisma.StringFilter<"FieldOption"> | string
  value?: Prisma.StringFilter<"FieldOption"> | string
  label?: Prisma.StringFilter<"FieldOption"> | string
  order?: Prisma.IntFilter<"FieldOption"> | number
  active?: Prisma.BoolFilter<"FieldOption"> | boolean
  createdAt?: Prisma.DateTimeFilter<"FieldOption"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FieldOption"> | Date | string
}

export type FieldOptionCreateManyFieldInput = {
  id?: string
  value: string
  label: string
  order?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FieldOptionUpdateWithoutFieldInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FieldOptionUncheckedUpdateWithoutFieldInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FieldOptionUncheckedUpdateManyWithoutFieldInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type FieldOptionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fieldId?: boolean
  value?: boolean
  label?: boolean
  order?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  field?: boolean | Prisma.FieldDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fieldOption"]>



export type FieldOptionSelectScalar = {
  id?: boolean
  fieldId?: boolean
  value?: boolean
  label?: boolean
  order?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type FieldOptionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "fieldId" | "value" | "label" | "order" | "active" | "createdAt" | "updatedAt", ExtArgs["result"]["fieldOption"]>
export type FieldOptionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  field?: boolean | Prisma.FieldDefaultArgs<ExtArgs>
}

export type $FieldOptionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FieldOption"
  objects: {
    field: Prisma.$FieldPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    fieldId: string
    value: string
    label: string
    order: number
    active: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["fieldOption"]>
  composites: {}
}

export type FieldOptionGetPayload<S extends boolean | null | undefined | FieldOptionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FieldOptionPayload, S>

export type FieldOptionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FieldOptionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FieldOptionCountAggregateInputType | true
  }

export interface FieldOptionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FieldOption'], meta: { name: 'FieldOption' } }
  /**
   * Find zero or one FieldOption that matches the filter.
   * @param {FieldOptionFindUniqueArgs} args - Arguments to find a FieldOption
   * @example
   * // Get one FieldOption
   * const fieldOption = await prisma.fieldOption.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FieldOptionFindUniqueArgs>(args: Prisma.SelectSubset<T, FieldOptionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FieldOptionClient<runtime.Types.Result.GetResult<Prisma.$FieldOptionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FieldOption that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FieldOptionFindUniqueOrThrowArgs} args - Arguments to find a FieldOption
   * @example
   * // Get one FieldOption
   * const fieldOption = await prisma.fieldOption.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FieldOptionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FieldOptionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FieldOptionClient<runtime.Types.Result.GetResult<Prisma.$FieldOptionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FieldOption that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldOptionFindFirstArgs} args - Arguments to find a FieldOption
   * @example
   * // Get one FieldOption
   * const fieldOption = await prisma.fieldOption.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FieldOptionFindFirstArgs>(args?: Prisma.SelectSubset<T, FieldOptionFindFirstArgs<ExtArgs>>): Prisma.Prisma__FieldOptionClient<runtime.Types.Result.GetResult<Prisma.$FieldOptionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FieldOption that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldOptionFindFirstOrThrowArgs} args - Arguments to find a FieldOption
   * @example
   * // Get one FieldOption
   * const fieldOption = await prisma.fieldOption.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FieldOptionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FieldOptionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FieldOptionClient<runtime.Types.Result.GetResult<Prisma.$FieldOptionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FieldOptions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldOptionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FieldOptions
   * const fieldOptions = await prisma.fieldOption.findMany()
   * 
   * // Get first 10 FieldOptions
   * const fieldOptions = await prisma.fieldOption.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const fieldOptionWithIdOnly = await prisma.fieldOption.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FieldOptionFindManyArgs>(args?: Prisma.SelectSubset<T, FieldOptionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FieldOptionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FieldOption.
   * @param {FieldOptionCreateArgs} args - Arguments to create a FieldOption.
   * @example
   * // Create one FieldOption
   * const FieldOption = await prisma.fieldOption.create({
   *   data: {
   *     // ... data to create a FieldOption
   *   }
   * })
   * 
   */
  create<T extends FieldOptionCreateArgs>(args: Prisma.SelectSubset<T, FieldOptionCreateArgs<ExtArgs>>): Prisma.Prisma__FieldOptionClient<runtime.Types.Result.GetResult<Prisma.$FieldOptionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FieldOptions.
   * @param {FieldOptionCreateManyArgs} args - Arguments to create many FieldOptions.
   * @example
   * // Create many FieldOptions
   * const fieldOption = await prisma.fieldOption.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FieldOptionCreateManyArgs>(args?: Prisma.SelectSubset<T, FieldOptionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a FieldOption.
   * @param {FieldOptionDeleteArgs} args - Arguments to delete one FieldOption.
   * @example
   * // Delete one FieldOption
   * const FieldOption = await prisma.fieldOption.delete({
   *   where: {
   *     // ... filter to delete one FieldOption
   *   }
   * })
   * 
   */
  delete<T extends FieldOptionDeleteArgs>(args: Prisma.SelectSubset<T, FieldOptionDeleteArgs<ExtArgs>>): Prisma.Prisma__FieldOptionClient<runtime.Types.Result.GetResult<Prisma.$FieldOptionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FieldOption.
   * @param {FieldOptionUpdateArgs} args - Arguments to update one FieldOption.
   * @example
   * // Update one FieldOption
   * const fieldOption = await prisma.fieldOption.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FieldOptionUpdateArgs>(args: Prisma.SelectSubset<T, FieldOptionUpdateArgs<ExtArgs>>): Prisma.Prisma__FieldOptionClient<runtime.Types.Result.GetResult<Prisma.$FieldOptionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FieldOptions.
   * @param {FieldOptionDeleteManyArgs} args - Arguments to filter FieldOptions to delete.
   * @example
   * // Delete a few FieldOptions
   * const { count } = await prisma.fieldOption.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FieldOptionDeleteManyArgs>(args?: Prisma.SelectSubset<T, FieldOptionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FieldOptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldOptionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FieldOptions
   * const fieldOption = await prisma.fieldOption.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FieldOptionUpdateManyArgs>(args: Prisma.SelectSubset<T, FieldOptionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one FieldOption.
   * @param {FieldOptionUpsertArgs} args - Arguments to update or create a FieldOption.
   * @example
   * // Update or create a FieldOption
   * const fieldOption = await prisma.fieldOption.upsert({
   *   create: {
   *     // ... data to create a FieldOption
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FieldOption we want to update
   *   }
   * })
   */
  upsert<T extends FieldOptionUpsertArgs>(args: Prisma.SelectSubset<T, FieldOptionUpsertArgs<ExtArgs>>): Prisma.Prisma__FieldOptionClient<runtime.Types.Result.GetResult<Prisma.$FieldOptionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FieldOptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldOptionCountArgs} args - Arguments to filter FieldOptions to count.
   * @example
   * // Count the number of FieldOptions
   * const count = await prisma.fieldOption.count({
   *   where: {
   *     // ... the filter for the FieldOptions we want to count
   *   }
   * })
  **/
  count<T extends FieldOptionCountArgs>(
    args?: Prisma.Subset<T, FieldOptionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FieldOptionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FieldOption.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldOptionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FieldOptionAggregateArgs>(args: Prisma.Subset<T, FieldOptionAggregateArgs>): Prisma.PrismaPromise<GetFieldOptionAggregateType<T>>

  /**
   * Group by FieldOption.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldOptionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FieldOptionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FieldOptionGroupByArgs['orderBy'] }
      : { orderBy?: FieldOptionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FieldOptionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFieldOptionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FieldOption model
 */
readonly fields: FieldOptionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FieldOption.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FieldOptionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  field<T extends Prisma.FieldDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FieldDefaultArgs<ExtArgs>>): Prisma.Prisma__FieldClient<runtime.Types.Result.GetResult<Prisma.$FieldPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FieldOption model
 */
export interface FieldOptionFieldRefs {
  readonly id: Prisma.FieldRef<"FieldOption", 'String'>
  readonly fieldId: Prisma.FieldRef<"FieldOption", 'String'>
  readonly value: Prisma.FieldRef<"FieldOption", 'String'>
  readonly label: Prisma.FieldRef<"FieldOption", 'String'>
  readonly order: Prisma.FieldRef<"FieldOption", 'Int'>
  readonly active: Prisma.FieldRef<"FieldOption", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"FieldOption", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"FieldOption", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FieldOption findUnique
 */
export type FieldOptionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldOption
   */
  select?: Prisma.FieldOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FieldOption
   */
  omit?: Prisma.FieldOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldOptionInclude<ExtArgs> | null
  /**
   * Filter, which FieldOption to fetch.
   */
  where: Prisma.FieldOptionWhereUniqueInput
}

/**
 * FieldOption findUniqueOrThrow
 */
export type FieldOptionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldOption
   */
  select?: Prisma.FieldOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FieldOption
   */
  omit?: Prisma.FieldOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldOptionInclude<ExtArgs> | null
  /**
   * Filter, which FieldOption to fetch.
   */
  where: Prisma.FieldOptionWhereUniqueInput
}

/**
 * FieldOption findFirst
 */
export type FieldOptionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldOption
   */
  select?: Prisma.FieldOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FieldOption
   */
  omit?: Prisma.FieldOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldOptionInclude<ExtArgs> | null
  /**
   * Filter, which FieldOption to fetch.
   */
  where?: Prisma.FieldOptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FieldOptions to fetch.
   */
  orderBy?: Prisma.FieldOptionOrderByWithRelationInput | Prisma.FieldOptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FieldOptions.
   */
  cursor?: Prisma.FieldOptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FieldOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FieldOptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FieldOptions.
   */
  distinct?: Prisma.FieldOptionScalarFieldEnum | Prisma.FieldOptionScalarFieldEnum[]
}

/**
 * FieldOption findFirstOrThrow
 */
export type FieldOptionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldOption
   */
  select?: Prisma.FieldOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FieldOption
   */
  omit?: Prisma.FieldOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldOptionInclude<ExtArgs> | null
  /**
   * Filter, which FieldOption to fetch.
   */
  where?: Prisma.FieldOptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FieldOptions to fetch.
   */
  orderBy?: Prisma.FieldOptionOrderByWithRelationInput | Prisma.FieldOptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FieldOptions.
   */
  cursor?: Prisma.FieldOptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FieldOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FieldOptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FieldOptions.
   */
  distinct?: Prisma.FieldOptionScalarFieldEnum | Prisma.FieldOptionScalarFieldEnum[]
}

/**
 * FieldOption findMany
 */
export type FieldOptionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldOption
   */
  select?: Prisma.FieldOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FieldOption
   */
  omit?: Prisma.FieldOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldOptionInclude<ExtArgs> | null
  /**
   * Filter, which FieldOptions to fetch.
   */
  where?: Prisma.FieldOptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FieldOptions to fetch.
   */
  orderBy?: Prisma.FieldOptionOrderByWithRelationInput | Prisma.FieldOptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FieldOptions.
   */
  cursor?: Prisma.FieldOptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FieldOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FieldOptions.
   */
  skip?: number
  distinct?: Prisma.FieldOptionScalarFieldEnum | Prisma.FieldOptionScalarFieldEnum[]
}

/**
 * FieldOption create
 */
export type FieldOptionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldOption
   */
  select?: Prisma.FieldOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FieldOption
   */
  omit?: Prisma.FieldOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldOptionInclude<ExtArgs> | null
  /**
   * The data needed to create a FieldOption.
   */
  data: Prisma.XOR<Prisma.FieldOptionCreateInput, Prisma.FieldOptionUncheckedCreateInput>
}

/**
 * FieldOption createMany
 */
export type FieldOptionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FieldOptions.
   */
  data: Prisma.FieldOptionCreateManyInput | Prisma.FieldOptionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FieldOption update
 */
export type FieldOptionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldOption
   */
  select?: Prisma.FieldOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FieldOption
   */
  omit?: Prisma.FieldOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldOptionInclude<ExtArgs> | null
  /**
   * The data needed to update a FieldOption.
   */
  data: Prisma.XOR<Prisma.FieldOptionUpdateInput, Prisma.FieldOptionUncheckedUpdateInput>
  /**
   * Choose, which FieldOption to update.
   */
  where: Prisma.FieldOptionWhereUniqueInput
}

/**
 * FieldOption updateMany
 */
export type FieldOptionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FieldOptions.
   */
  data: Prisma.XOR<Prisma.FieldOptionUpdateManyMutationInput, Prisma.FieldOptionUncheckedUpdateManyInput>
  /**
   * Filter which FieldOptions to update
   */
  where?: Prisma.FieldOptionWhereInput
  /**
   * Limit how many FieldOptions to update.
   */
  limit?: number
}

/**
 * FieldOption upsert
 */
export type FieldOptionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldOption
   */
  select?: Prisma.FieldOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FieldOption
   */
  omit?: Prisma.FieldOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldOptionInclude<ExtArgs> | null
  /**
   * The filter to search for the FieldOption to update in case it exists.
   */
  where: Prisma.FieldOptionWhereUniqueInput
  /**
   * In case the FieldOption found by the `where` argument doesn't exist, create a new FieldOption with this data.
   */
  create: Prisma.XOR<Prisma.FieldOptionCreateInput, Prisma.FieldOptionUncheckedCreateInput>
  /**
   * In case the FieldOption was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FieldOptionUpdateInput, Prisma.FieldOptionUncheckedUpdateInput>
}

/**
 * FieldOption delete
 */
export type FieldOptionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldOption
   */
  select?: Prisma.FieldOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FieldOption
   */
  omit?: Prisma.FieldOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldOptionInclude<ExtArgs> | null
  /**
   * Filter which FieldOption to delete.
   */
  where: Prisma.FieldOptionWhereUniqueInput
}

/**
 * FieldOption deleteMany
 */
export type FieldOptionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FieldOptions to delete
   */
  where?: Prisma.FieldOptionWhereInput
  /**
   * Limit how many FieldOptions to delete.
   */
  limit?: number
}

/**
 * FieldOption without action
 */
export type FieldOptionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldOption
   */
  select?: Prisma.FieldOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FieldOption
   */
  omit?: Prisma.FieldOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldOptionInclude<ExtArgs> | null
}
