
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Field` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Field
 * 
 */
export type FieldModel = runtime.Types.Result.DefaultSelection<Prisma.$FieldPayload>

export type AggregateField = {
  _count: FieldCountAggregateOutputType | null
  _avg: FieldAvgAggregateOutputType | null
  _sum: FieldSumAggregateOutputType | null
  _min: FieldMinAggregateOutputType | null
  _max: FieldMaxAggregateOutputType | null
}

export type FieldAvgAggregateOutputType = {
  minLength: number | null
  maxLength: number | null
  order: number | null
}

export type FieldSumAggregateOutputType = {
  minLength: number | null
  maxLength: number | null
  order: number | null
}

export type FieldMinAggregateOutputType = {
  id: string | null
  tenantId: string | null
  organizationId: string | null
  context: string | null
  key: string | null
  label: string | null
  type: $Enums.FieldType | null
  comparator: $Enums.FieldComparator | null
  required: boolean | null
  minLength: number | null
  maxLength: number | null
  pattern: string | null
  placeholder: string | null
  group: string | null
  order: number | null
  active: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FieldMaxAggregateOutputType = {
  id: string | null
  tenantId: string | null
  organizationId: string | null
  context: string | null
  key: string | null
  label: string | null
  type: $Enums.FieldType | null
  comparator: $Enums.FieldComparator | null
  required: boolean | null
  minLength: number | null
  maxLength: number | null
  pattern: string | null
  placeholder: string | null
  group: string | null
  order: number | null
  active: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FieldCountAggregateOutputType = {
  id: number
  tenantId: number
  organizationId: number
  context: number
  key: number
  label: number
  type: number
  comparator: number
  required: number
  minLength: number
  maxLength: number
  pattern: number
  placeholder: number
  group: number
  order: number
  active: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type FieldAvgAggregateInputType = {
  minLength?: true
  maxLength?: true
  order?: true
}

export type FieldSumAggregateInputType = {
  minLength?: true
  maxLength?: true
  order?: true
}

export type FieldMinAggregateInputType = {
  id?: true
  tenantId?: true
  organizationId?: true
  context?: true
  key?: true
  label?: true
  type?: true
  comparator?: true
  required?: true
  minLength?: true
  maxLength?: true
  pattern?: true
  placeholder?: true
  group?: true
  order?: true
  active?: true
  createdAt?: true
  updatedAt?: true
}

export type FieldMaxAggregateInputType = {
  id?: true
  tenantId?: true
  organizationId?: true
  context?: true
  key?: true
  label?: true
  type?: true
  comparator?: true
  required?: true
  minLength?: true
  maxLength?: true
  pattern?: true
  placeholder?: true
  group?: true
  order?: true
  active?: true
  createdAt?: true
  updatedAt?: true
}

export type FieldCountAggregateInputType = {
  id?: true
  tenantId?: true
  organizationId?: true
  context?: true
  key?: true
  label?: true
  type?: true
  comparator?: true
  required?: true
  minLength?: true
  maxLength?: true
  pattern?: true
  placeholder?: true
  group?: true
  order?: true
  active?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type FieldAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Field to aggregate.
   */
  where?: Prisma.FieldWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Fields to fetch.
   */
  orderBy?: Prisma.FieldOrderByWithRelationInput | Prisma.FieldOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FieldWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Fields from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Fields.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Fields
  **/
  _count?: true | FieldCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FieldAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FieldSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FieldMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FieldMaxAggregateInputType
}

export type GetFieldAggregateType<T extends FieldAggregateArgs> = {
      [P in keyof T & keyof AggregateField]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateField[P]>
    : Prisma.GetScalarType<T[P], AggregateField[P]>
}




export type FieldGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FieldWhereInput
  orderBy?: Prisma.FieldOrderByWithAggregationInput | Prisma.FieldOrderByWithAggregationInput[]
  by: Prisma.FieldScalarFieldEnum[] | Prisma.FieldScalarFieldEnum
  having?: Prisma.FieldScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FieldCountAggregateInputType | true
  _avg?: FieldAvgAggregateInputType
  _sum?: FieldSumAggregateInputType
  _min?: FieldMinAggregateInputType
  _max?: FieldMaxAggregateInputType
}

export type FieldGroupByOutputType = {
  id: string
  tenantId: string
  organizationId: string
  context: string
  key: string
  label: string
  type: $Enums.FieldType
  comparator: $Enums.FieldComparator
  required: boolean
  minLength: number | null
  maxLength: number | null
  pattern: string | null
  placeholder: string | null
  group: string
  order: number
  active: boolean
  createdAt: Date
  updatedAt: Date
  _count: FieldCountAggregateOutputType | null
  _avg: FieldAvgAggregateOutputType | null
  _sum: FieldSumAggregateOutputType | null
  _min: FieldMinAggregateOutputType | null
  _max: FieldMaxAggregateOutputType | null
}

type GetFieldGroupByPayload<T extends FieldGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FieldGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FieldGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FieldGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FieldGroupByOutputType[P]>
      }
    >
  >



export type FieldWhereInput = {
  AND?: Prisma.FieldWhereInput | Prisma.FieldWhereInput[]
  OR?: Prisma.FieldWhereInput[]
  NOT?: Prisma.FieldWhereInput | Prisma.FieldWhereInput[]
  id?: Prisma.StringFilter<"Field"> | string
  tenantId?: Prisma.StringFilter<"Field"> | string
  organizationId?: Prisma.StringFilter<"Field"> | string
  context?: Prisma.StringFilter<"Field"> | string
  key?: Prisma.StringFilter<"Field"> | string
  label?: Prisma.StringFilter<"Field"> | string
  type?: Prisma.EnumFieldTypeFilter<"Field"> | $Enums.FieldType
  comparator?: Prisma.EnumFieldComparatorFilter<"Field"> | $Enums.FieldComparator
  required?: Prisma.BoolFilter<"Field"> | boolean
  minLength?: Prisma.IntNullableFilter<"Field"> | number | null
  maxLength?: Prisma.IntNullableFilter<"Field"> | number | null
  pattern?: Prisma.StringNullableFilter<"Field"> | string | null
  placeholder?: Prisma.StringNullableFilter<"Field"> | string | null
  group?: Prisma.StringFilter<"Field"> | string
  order?: Prisma.IntFilter<"Field"> | number
  active?: Prisma.BoolFilter<"Field"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Field"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Field"> | Date | string
  options?: Prisma.FieldOptionListRelationFilter
  values?: Prisma.FieldValueListRelationFilter
}

export type FieldOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  context?: Prisma.SortOrder
  key?: Prisma.SortOrder
  label?: Prisma.SortOrder
  type?: Prisma.SortOrder
  comparator?: Prisma.SortOrder
  required?: Prisma.SortOrder
  minLength?: Prisma.SortOrderInput | Prisma.SortOrder
  maxLength?: Prisma.SortOrderInput | Prisma.SortOrder
  pattern?: Prisma.SortOrderInput | Prisma.SortOrder
  placeholder?: Prisma.SortOrderInput | Prisma.SortOrder
  group?: Prisma.SortOrder
  order?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  options?: Prisma.FieldOptionOrderByRelationAggregateInput
  values?: Prisma.FieldValueOrderByRelationAggregateInput
  _relevance?: Prisma.FieldOrderByRelevanceInput
}

export type FieldWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  tenantId_organizationId_context_key?: Prisma.FieldTenantIdOrganizationIdContextKeyCompoundUniqueInput
  AND?: Prisma.FieldWhereInput | Prisma.FieldWhereInput[]
  OR?: Prisma.FieldWhereInput[]
  NOT?: Prisma.FieldWhereInput | Prisma.FieldWhereInput[]
  tenantId?: Prisma.StringFilter<"Field"> | string
  organizationId?: Prisma.StringFilter<"Field"> | string
  context?: Prisma.StringFilter<"Field"> | string
  key?: Prisma.StringFilter<"Field"> | string
  label?: Prisma.StringFilter<"Field"> | string
  type?: Prisma.EnumFieldTypeFilter<"Field"> | $Enums.FieldType
  comparator?: Prisma.EnumFieldComparatorFilter<"Field"> | $Enums.FieldComparator
  required?: Prisma.BoolFilter<"Field"> | boolean
  minLength?: Prisma.IntNullableFilter<"Field"> | number | null
  maxLength?: Prisma.IntNullableFilter<"Field"> | number | null
  pattern?: Prisma.StringNullableFilter<"Field"> | string | null
  placeholder?: Prisma.StringNullableFilter<"Field"> | string | null
  group?: Prisma.StringFilter<"Field"> | string
  order?: Prisma.IntFilter<"Field"> | number
  active?: Prisma.BoolFilter<"Field"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Field"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Field"> | Date | string
  options?: Prisma.FieldOptionListRelationFilter
  values?: Prisma.FieldValueListRelationFilter
}, "id" | "tenantId_organizationId_context_key">

export type FieldOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  context?: Prisma.SortOrder
  key?: Prisma.SortOrder
  label?: Prisma.SortOrder
  type?: Prisma.SortOrder
  comparator?: Prisma.SortOrder
  required?: Prisma.SortOrder
  minLength?: Prisma.SortOrderInput | Prisma.SortOrder
  maxLength?: Prisma.SortOrderInput | Prisma.SortOrder
  pattern?: Prisma.SortOrderInput | Prisma.SortOrder
  placeholder?: Prisma.SortOrderInput | Prisma.SortOrder
  group?: Prisma.SortOrder
  order?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.FieldCountOrderByAggregateInput
  _avg?: Prisma.FieldAvgOrderByAggregateInput
  _max?: Prisma.FieldMaxOrderByAggregateInput
  _min?: Prisma.FieldMinOrderByAggregateInput
  _sum?: Prisma.FieldSumOrderByAggregateInput
}

export type FieldScalarWhereWithAggregatesInput = {
  AND?: Prisma.FieldScalarWhereWithAggregatesInput | Prisma.FieldScalarWhereWithAggregatesInput[]
  OR?: Prisma.FieldScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FieldScalarWhereWithAggregatesInput | Prisma.FieldScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Field"> | string
  tenantId?: Prisma.StringWithAggregatesFilter<"Field"> | string
  organizationId?: Prisma.StringWithAggregatesFilter<"Field"> | string
  context?: Prisma.StringWithAggregatesFilter<"Field"> | string
  key?: Prisma.StringWithAggregatesFilter<"Field"> | string
  label?: Prisma.StringWithAggregatesFilter<"Field"> | string
  type?: Prisma.EnumFieldTypeWithAggregatesFilter<"Field"> | $Enums.FieldType
  comparator?: Prisma.EnumFieldComparatorWithAggregatesFilter<"Field"> | $Enums.FieldComparator
  required?: Prisma.BoolWithAggregatesFilter<"Field"> | boolean
  minLength?: Prisma.IntNullableWithAggregatesFilter<"Field"> | number | null
  maxLength?: Prisma.IntNullableWithAggregatesFilter<"Field"> | number | null
  pattern?: Prisma.StringNullableWithAggregatesFilter<"Field"> | string | null
  placeholder?: Prisma.StringNullableWithAggregatesFilter<"Field"> | string | null
  group?: Prisma.StringWithAggregatesFilter<"Field"> | string
  order?: Prisma.IntWithAggregatesFilter<"Field"> | number
  active?: Prisma.BoolWithAggregatesFilter<"Field"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Field"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Field"> | Date | string
}

export type FieldCreateInput = {
  id?: string
  tenantId: string
  organizationId: string
  context: string
  key: string
  label: string
  type: $Enums.FieldType
  comparator: $Enums.FieldComparator
  required?: boolean
  minLength?: number | null
  maxLength?: number | null
  pattern?: string | null
  placeholder?: string | null
  group: string
  order?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  options?: Prisma.FieldOptionCreateNestedManyWithoutFieldInput
  values?: Prisma.FieldValueCreateNestedManyWithoutFieldInput
}

export type FieldUncheckedCreateInput = {
  id?: string
  tenantId: string
  organizationId: string
  context: string
  key: string
  label: string
  type: $Enums.FieldType
  comparator: $Enums.FieldComparator
  required?: boolean
  minLength?: number | null
  maxLength?: number | null
  pattern?: string | null
  placeholder?: string | null
  group: string
  order?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  options?: Prisma.FieldOptionUncheckedCreateNestedManyWithoutFieldInput
  values?: Prisma.FieldValueUncheckedCreateNestedManyWithoutFieldInput
}

export type FieldUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFieldTypeFieldUpdateOperationsInput | $Enums.FieldType
  comparator?: Prisma.EnumFieldComparatorFieldUpdateOperationsInput | $Enums.FieldComparator
  required?: Prisma.BoolFieldUpdateOperationsInput | boolean
  minLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  pattern?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  placeholder?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  group?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  options?: Prisma.FieldOptionUpdateManyWithoutFieldNestedInput
  values?: Prisma.FieldValueUpdateManyWithoutFieldNestedInput
}

export type FieldUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFieldTypeFieldUpdateOperationsInput | $Enums.FieldType
  comparator?: Prisma.EnumFieldComparatorFieldUpdateOperationsInput | $Enums.FieldComparator
  required?: Prisma.BoolFieldUpdateOperationsInput | boolean
  minLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  pattern?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  placeholder?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  group?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  options?: Prisma.FieldOptionUncheckedUpdateManyWithoutFieldNestedInput
  values?: Prisma.FieldValueUncheckedUpdateManyWithoutFieldNestedInput
}

export type FieldCreateManyInput = {
  id?: string
  tenantId: string
  organizationId: string
  context: string
  key: string
  label: string
  type: $Enums.FieldType
  comparator: $Enums.FieldComparator
  required?: boolean
  minLength?: number | null
  maxLength?: number | null
  pattern?: string | null
  placeholder?: string | null
  group: string
  order?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FieldUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFieldTypeFieldUpdateOperationsInput | $Enums.FieldType
  comparator?: Prisma.EnumFieldComparatorFieldUpdateOperationsInput | $Enums.FieldComparator
  required?: Prisma.BoolFieldUpdateOperationsInput | boolean
  minLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  pattern?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  placeholder?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  group?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FieldUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFieldTypeFieldUpdateOperationsInput | $Enums.FieldType
  comparator?: Prisma.EnumFieldComparatorFieldUpdateOperationsInput | $Enums.FieldComparator
  required?: Prisma.BoolFieldUpdateOperationsInput | boolean
  minLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  pattern?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  placeholder?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  group?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FieldOrderByRelevanceInput = {
  fields: Prisma.FieldOrderByRelevanceFieldEnum | Prisma.FieldOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type FieldTenantIdOrganizationIdContextKeyCompoundUniqueInput = {
  tenantId: string
  organizationId: string
  context: string
  key: string
}

export type FieldCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  context?: Prisma.SortOrder
  key?: Prisma.SortOrder
  label?: Prisma.SortOrder
  type?: Prisma.SortOrder
  comparator?: Prisma.SortOrder
  required?: Prisma.SortOrder
  minLength?: Prisma.SortOrder
  maxLength?: Prisma.SortOrder
  pattern?: Prisma.SortOrder
  placeholder?: Prisma.SortOrder
  group?: Prisma.SortOrder
  order?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FieldAvgOrderByAggregateInput = {
  minLength?: Prisma.SortOrder
  maxLength?: Prisma.SortOrder
  order?: Prisma.SortOrder
}

export type FieldMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  context?: Prisma.SortOrder
  key?: Prisma.SortOrder
  label?: Prisma.SortOrder
  type?: Prisma.SortOrder
  comparator?: Prisma.SortOrder
  required?: Prisma.SortOrder
  minLength?: Prisma.SortOrder
  maxLength?: Prisma.SortOrder
  pattern?: Prisma.SortOrder
  placeholder?: Prisma.SortOrder
  group?: Prisma.SortOrder
  order?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FieldMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tenantId?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  context?: Prisma.SortOrder
  key?: Prisma.SortOrder
  label?: Prisma.SortOrder
  type?: Prisma.SortOrder
  comparator?: Prisma.SortOrder
  required?: Prisma.SortOrder
  minLength?: Prisma.SortOrder
  maxLength?: Prisma.SortOrder
  pattern?: Prisma.SortOrder
  placeholder?: Prisma.SortOrder
  group?: Prisma.SortOrder
  order?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FieldSumOrderByAggregateInput = {
  minLength?: Prisma.SortOrder
  maxLength?: Prisma.SortOrder
  order?: Prisma.SortOrder
}

export type FieldScalarRelationFilter = {
  is?: Prisma.FieldWhereInput
  isNot?: Prisma.FieldWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type EnumFieldTypeFieldUpdateOperationsInput = {
  set?: $Enums.FieldType
}

export type EnumFieldComparatorFieldUpdateOperationsInput = {
  set?: $Enums.FieldComparator
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type FieldCreateNestedOneWithoutOptionsInput = {
  create?: Prisma.XOR<Prisma.FieldCreateWithoutOptionsInput, Prisma.FieldUncheckedCreateWithoutOptionsInput>
  connectOrCreate?: Prisma.FieldCreateOrConnectWithoutOptionsInput
  connect?: Prisma.FieldWhereUniqueInput
}

export type FieldUpdateOneRequiredWithoutOptionsNestedInput = {
  create?: Prisma.XOR<Prisma.FieldCreateWithoutOptionsInput, Prisma.FieldUncheckedCreateWithoutOptionsInput>
  connectOrCreate?: Prisma.FieldCreateOrConnectWithoutOptionsInput
  upsert?: Prisma.FieldUpsertWithoutOptionsInput
  connect?: Prisma.FieldWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FieldUpdateToOneWithWhereWithoutOptionsInput, Prisma.FieldUpdateWithoutOptionsInput>, Prisma.FieldUncheckedUpdateWithoutOptionsInput>
}

export type FieldCreateNestedOneWithoutValuesInput = {
  create?: Prisma.XOR<Prisma.FieldCreateWithoutValuesInput, Prisma.FieldUncheckedCreateWithoutValuesInput>
  connectOrCreate?: Prisma.FieldCreateOrConnectWithoutValuesInput
  connect?: Prisma.FieldWhereUniqueInput
}

export type FieldUpdateOneRequiredWithoutValuesNestedInput = {
  create?: Prisma.XOR<Prisma.FieldCreateWithoutValuesInput, Prisma.FieldUncheckedCreateWithoutValuesInput>
  connectOrCreate?: Prisma.FieldCreateOrConnectWithoutValuesInput
  upsert?: Prisma.FieldUpsertWithoutValuesInput
  connect?: Prisma.FieldWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FieldUpdateToOneWithWhereWithoutValuesInput, Prisma.FieldUpdateWithoutValuesInput>, Prisma.FieldUncheckedUpdateWithoutValuesInput>
}

export type FieldCreateWithoutOptionsInput = {
  id?: string
  tenantId: string
  organizationId: string
  context: string
  key: string
  label: string
  type: $Enums.FieldType
  comparator: $Enums.FieldComparator
  required?: boolean
  minLength?: number | null
  maxLength?: number | null
  pattern?: string | null
  placeholder?: string | null
  group: string
  order?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  values?: Prisma.FieldValueCreateNestedManyWithoutFieldInput
}

export type FieldUncheckedCreateWithoutOptionsInput = {
  id?: string
  tenantId: string
  organizationId: string
  context: string
  key: string
  label: string
  type: $Enums.FieldType
  comparator: $Enums.FieldComparator
  required?: boolean
  minLength?: number | null
  maxLength?: number | null
  pattern?: string | null
  placeholder?: string | null
  group: string
  order?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  values?: Prisma.FieldValueUncheckedCreateNestedManyWithoutFieldInput
}

export type FieldCreateOrConnectWithoutOptionsInput = {
  where: Prisma.FieldWhereUniqueInput
  create: Prisma.XOR<Prisma.FieldCreateWithoutOptionsInput, Prisma.FieldUncheckedCreateWithoutOptionsInput>
}

export type FieldUpsertWithoutOptionsInput = {
  update: Prisma.XOR<Prisma.FieldUpdateWithoutOptionsInput, Prisma.FieldUncheckedUpdateWithoutOptionsInput>
  create: Prisma.XOR<Prisma.FieldCreateWithoutOptionsInput, Prisma.FieldUncheckedCreateWithoutOptionsInput>
  where?: Prisma.FieldWhereInput
}

export type FieldUpdateToOneWithWhereWithoutOptionsInput = {
  where?: Prisma.FieldWhereInput
  data: Prisma.XOR<Prisma.FieldUpdateWithoutOptionsInput, Prisma.FieldUncheckedUpdateWithoutOptionsInput>
}

export type FieldUpdateWithoutOptionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFieldTypeFieldUpdateOperationsInput | $Enums.FieldType
  comparator?: Prisma.EnumFieldComparatorFieldUpdateOperationsInput | $Enums.FieldComparator
  required?: Prisma.BoolFieldUpdateOperationsInput | boolean
  minLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  pattern?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  placeholder?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  group?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  values?: Prisma.FieldValueUpdateManyWithoutFieldNestedInput
}

export type FieldUncheckedUpdateWithoutOptionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFieldTypeFieldUpdateOperationsInput | $Enums.FieldType
  comparator?: Prisma.EnumFieldComparatorFieldUpdateOperationsInput | $Enums.FieldComparator
  required?: Prisma.BoolFieldUpdateOperationsInput | boolean
  minLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  pattern?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  placeholder?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  group?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  values?: Prisma.FieldValueUncheckedUpdateManyWithoutFieldNestedInput
}

export type FieldCreateWithoutValuesInput = {
  id?: string
  tenantId: string
  organizationId: string
  context: string
  key: string
  label: string
  type: $Enums.FieldType
  comparator: $Enums.FieldComparator
  required?: boolean
  minLength?: number | null
  maxLength?: number | null
  pattern?: string | null
  placeholder?: string | null
  group: string
  order?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  options?: Prisma.FieldOptionCreateNestedManyWithoutFieldInput
}

export type FieldUncheckedCreateWithoutValuesInput = {
  id?: string
  tenantId: string
  organizationId: string
  context: string
  key: string
  label: string
  type: $Enums.FieldType
  comparator: $Enums.FieldComparator
  required?: boolean
  minLength?: number | null
  maxLength?: number | null
  pattern?: string | null
  placeholder?: string | null
  group: string
  order?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  options?: Prisma.FieldOptionUncheckedCreateNestedManyWithoutFieldInput
}

export type FieldCreateOrConnectWithoutValuesInput = {
  where: Prisma.FieldWhereUniqueInput
  create: Prisma.XOR<Prisma.FieldCreateWithoutValuesInput, Prisma.FieldUncheckedCreateWithoutValuesInput>
}

export type FieldUpsertWithoutValuesInput = {
  update: Prisma.XOR<Prisma.FieldUpdateWithoutValuesInput, Prisma.FieldUncheckedUpdateWithoutValuesInput>
  create: Prisma.XOR<Prisma.FieldCreateWithoutValuesInput, Prisma.FieldUncheckedCreateWithoutValuesInput>
  where?: Prisma.FieldWhereInput
}

export type FieldUpdateToOneWithWhereWithoutValuesInput = {
  where?: Prisma.FieldWhereInput
  data: Prisma.XOR<Prisma.FieldUpdateWithoutValuesInput, Prisma.FieldUncheckedUpdateWithoutValuesInput>
}

export type FieldUpdateWithoutValuesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFieldTypeFieldUpdateOperationsInput | $Enums.FieldType
  comparator?: Prisma.EnumFieldComparatorFieldUpdateOperationsInput | $Enums.FieldComparator
  required?: Prisma.BoolFieldUpdateOperationsInput | boolean
  minLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  pattern?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  placeholder?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  group?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  options?: Prisma.FieldOptionUpdateManyWithoutFieldNestedInput
}

export type FieldUncheckedUpdateWithoutValuesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tenantId?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFieldTypeFieldUpdateOperationsInput | $Enums.FieldType
  comparator?: Prisma.EnumFieldComparatorFieldUpdateOperationsInput | $Enums.FieldComparator
  required?: Prisma.BoolFieldUpdateOperationsInput | boolean
  minLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  maxLength?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  pattern?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  placeholder?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  group?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  options?: Prisma.FieldOptionUncheckedUpdateManyWithoutFieldNestedInput
}


/**
 * Count Type FieldCountOutputType
 */

export type FieldCountOutputType = {
  options: number
  values: number
}

export type FieldCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  options?: boolean | FieldCountOutputTypeCountOptionsArgs
  values?: boolean | FieldCountOutputTypeCountValuesArgs
}

/**
 * FieldCountOutputType without action
 */
export type FieldCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldCountOutputType
   */
  select?: Prisma.FieldCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FieldCountOutputType without action
 */
export type FieldCountOutputTypeCountOptionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FieldOptionWhereInput
}

/**
 * FieldCountOutputType without action
 */
export type FieldCountOutputTypeCountValuesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FieldValueWhereInput
}


export type FieldSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tenantId?: boolean
  organizationId?: boolean
  context?: boolean
  key?: boolean
  label?: boolean
  type?: boolean
  comparator?: boolean
  required?: boolean
  minLength?: boolean
  maxLength?: boolean
  pattern?: boolean
  placeholder?: boolean
  group?: boolean
  order?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  options?: boolean | Prisma.Field$optionsArgs<ExtArgs>
  values?: boolean | Prisma.Field$valuesArgs<ExtArgs>
  _count?: boolean | Prisma.FieldCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["field"]>



export type FieldSelectScalar = {
  id?: boolean
  tenantId?: boolean
  organizationId?: boolean
  context?: boolean
  key?: boolean
  label?: boolean
  type?: boolean
  comparator?: boolean
  required?: boolean
  minLength?: boolean
  maxLength?: boolean
  pattern?: boolean
  placeholder?: boolean
  group?: boolean
  order?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type FieldOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tenantId" | "organizationId" | "context" | "key" | "label" | "type" | "comparator" | "required" | "minLength" | "maxLength" | "pattern" | "placeholder" | "group" | "order" | "active" | "createdAt" | "updatedAt", ExtArgs["result"]["field"]>
export type FieldInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  options?: boolean | Prisma.Field$optionsArgs<ExtArgs>
  values?: boolean | Prisma.Field$valuesArgs<ExtArgs>
  _count?: boolean | Prisma.FieldCountOutputTypeDefaultArgs<ExtArgs>
}

export type $FieldPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Field"
  objects: {
    options: Prisma.$FieldOptionPayload<ExtArgs>[]
    values: Prisma.$FieldValuePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    tenantId: string
    organizationId: string
    context: string
    key: string
    label: string
    type: $Enums.FieldType
    comparator: $Enums.FieldComparator
    required: boolean
    minLength: number | null
    maxLength: number | null
    pattern: string | null
    placeholder: string | null
    group: string
    order: number
    active: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["field"]>
  composites: {}
}

export type FieldGetPayload<S extends boolean | null | undefined | FieldDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FieldPayload, S>

export type FieldCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FieldFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FieldCountAggregateInputType | true
  }

export interface FieldDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Field'], meta: { name: 'Field' } }
  /**
   * Find zero or one Field that matches the filter.
   * @param {FieldFindUniqueArgs} args - Arguments to find a Field
   * @example
   * // Get one Field
   * const field = await prisma.field.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FieldFindUniqueArgs>(args: Prisma.SelectSubset<T, FieldFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FieldClient<runtime.Types.Result.GetResult<Prisma.$FieldPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Field that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FieldFindUniqueOrThrowArgs} args - Arguments to find a Field
   * @example
   * // Get one Field
   * const field = await prisma.field.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FieldFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FieldFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FieldClient<runtime.Types.Result.GetResult<Prisma.$FieldPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Field that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldFindFirstArgs} args - Arguments to find a Field
   * @example
   * // Get one Field
   * const field = await prisma.field.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FieldFindFirstArgs>(args?: Prisma.SelectSubset<T, FieldFindFirstArgs<ExtArgs>>): Prisma.Prisma__FieldClient<runtime.Types.Result.GetResult<Prisma.$FieldPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Field that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldFindFirstOrThrowArgs} args - Arguments to find a Field
   * @example
   * // Get one Field
   * const field = await prisma.field.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FieldFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FieldFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FieldClient<runtime.Types.Result.GetResult<Prisma.$FieldPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Fields that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Fields
   * const fields = await prisma.field.findMany()
   * 
   * // Get first 10 Fields
   * const fields = await prisma.field.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const fieldWithIdOnly = await prisma.field.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FieldFindManyArgs>(args?: Prisma.SelectSubset<T, FieldFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FieldPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Field.
   * @param {FieldCreateArgs} args - Arguments to create a Field.
   * @example
   * // Create one Field
   * const Field = await prisma.field.create({
   *   data: {
   *     // ... data to create a Field
   *   }
   * })
   * 
   */
  create<T extends FieldCreateArgs>(args: Prisma.SelectSubset<T, FieldCreateArgs<ExtArgs>>): Prisma.Prisma__FieldClient<runtime.Types.Result.GetResult<Prisma.$FieldPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Fields.
   * @param {FieldCreateManyArgs} args - Arguments to create many Fields.
   * @example
   * // Create many Fields
   * const field = await prisma.field.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FieldCreateManyArgs>(args?: Prisma.SelectSubset<T, FieldCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Field.
   * @param {FieldDeleteArgs} args - Arguments to delete one Field.
   * @example
   * // Delete one Field
   * const Field = await prisma.field.delete({
   *   where: {
   *     // ... filter to delete one Field
   *   }
   * })
   * 
   */
  delete<T extends FieldDeleteArgs>(args: Prisma.SelectSubset<T, FieldDeleteArgs<ExtArgs>>): Prisma.Prisma__FieldClient<runtime.Types.Result.GetResult<Prisma.$FieldPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Field.
   * @param {FieldUpdateArgs} args - Arguments to update one Field.
   * @example
   * // Update one Field
   * const field = await prisma.field.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FieldUpdateArgs>(args: Prisma.SelectSubset<T, FieldUpdateArgs<ExtArgs>>): Prisma.Prisma__FieldClient<runtime.Types.Result.GetResult<Prisma.$FieldPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Fields.
   * @param {FieldDeleteManyArgs} args - Arguments to filter Fields to delete.
   * @example
   * // Delete a few Fields
   * const { count } = await prisma.field.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FieldDeleteManyArgs>(args?: Prisma.SelectSubset<T, FieldDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Fields.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Fields
   * const field = await prisma.field.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FieldUpdateManyArgs>(args: Prisma.SelectSubset<T, FieldUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Field.
   * @param {FieldUpsertArgs} args - Arguments to update or create a Field.
   * @example
   * // Update or create a Field
   * const field = await prisma.field.upsert({
   *   create: {
   *     // ... data to create a Field
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Field we want to update
   *   }
   * })
   */
  upsert<T extends FieldUpsertArgs>(args: Prisma.SelectSubset<T, FieldUpsertArgs<ExtArgs>>): Prisma.Prisma__FieldClient<runtime.Types.Result.GetResult<Prisma.$FieldPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Fields.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldCountArgs} args - Arguments to filter Fields to count.
   * @example
   * // Count the number of Fields
   * const count = await prisma.field.count({
   *   where: {
   *     // ... the filter for the Fields we want to count
   *   }
   * })
  **/
  count<T extends FieldCountArgs>(
    args?: Prisma.Subset<T, FieldCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FieldCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Field.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FieldAggregateArgs>(args: Prisma.Subset<T, FieldAggregateArgs>): Prisma.PrismaPromise<GetFieldAggregateType<T>>

  /**
   * Group by Field.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FieldGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FieldGroupByArgs['orderBy'] }
      : { orderBy?: FieldGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FieldGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFieldGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Field model
 */
readonly fields: FieldFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Field.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FieldClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  options<T extends Prisma.Field$optionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Field$optionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FieldOptionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  values<T extends Prisma.Field$valuesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Field$valuesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FieldValuePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Field model
 */
export interface FieldFieldRefs {
  readonly id: Prisma.FieldRef<"Field", 'String'>
  readonly tenantId: Prisma.FieldRef<"Field", 'String'>
  readonly organizationId: Prisma.FieldRef<"Field", 'String'>
  readonly context: Prisma.FieldRef<"Field", 'String'>
  readonly key: Prisma.FieldRef<"Field", 'String'>
  readonly label: Prisma.FieldRef<"Field", 'String'>
  readonly type: Prisma.FieldRef<"Field", 'FieldType'>
  readonly comparator: Prisma.FieldRef<"Field", 'FieldComparator'>
  readonly required: Prisma.FieldRef<"Field", 'Boolean'>
  readonly minLength: Prisma.FieldRef<"Field", 'Int'>
  readonly maxLength: Prisma.FieldRef<"Field", 'Int'>
  readonly pattern: Prisma.FieldRef<"Field", 'String'>
  readonly placeholder: Prisma.FieldRef<"Field", 'String'>
  readonly group: Prisma.FieldRef<"Field", 'String'>
  readonly order: Prisma.FieldRef<"Field", 'Int'>
  readonly active: Prisma.FieldRef<"Field", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"Field", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Field", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Field findUnique
 */
export type FieldFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Field
   */
  select?: Prisma.FieldSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Field
   */
  omit?: Prisma.FieldOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldInclude<ExtArgs> | null
  /**
   * Filter, which Field to fetch.
   */
  where: Prisma.FieldWhereUniqueInput
}

/**
 * Field findUniqueOrThrow
 */
export type FieldFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Field
   */
  select?: Prisma.FieldSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Field
   */
  omit?: Prisma.FieldOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldInclude<ExtArgs> | null
  /**
   * Filter, which Field to fetch.
   */
  where: Prisma.FieldWhereUniqueInput
}

/**
 * Field findFirst
 */
export type FieldFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Field
   */
  select?: Prisma.FieldSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Field
   */
  omit?: Prisma.FieldOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldInclude<ExtArgs> | null
  /**
   * Filter, which Field to fetch.
   */
  where?: Prisma.FieldWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Fields to fetch.
   */
  orderBy?: Prisma.FieldOrderByWithRelationInput | Prisma.FieldOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Fields.
   */
  cursor?: Prisma.FieldWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Fields from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Fields.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Fields.
   */
  distinct?: Prisma.FieldScalarFieldEnum | Prisma.FieldScalarFieldEnum[]
}

/**
 * Field findFirstOrThrow
 */
export type FieldFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Field
   */
  select?: Prisma.FieldSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Field
   */
  omit?: Prisma.FieldOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldInclude<ExtArgs> | null
  /**
   * Filter, which Field to fetch.
   */
  where?: Prisma.FieldWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Fields to fetch.
   */
  orderBy?: Prisma.FieldOrderByWithRelationInput | Prisma.FieldOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Fields.
   */
  cursor?: Prisma.FieldWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Fields from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Fields.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Fields.
   */
  distinct?: Prisma.FieldScalarFieldEnum | Prisma.FieldScalarFieldEnum[]
}

/**
 * Field findMany
 */
export type FieldFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Field
   */
  select?: Prisma.FieldSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Field
   */
  omit?: Prisma.FieldOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldInclude<ExtArgs> | null
  /**
   * Filter, which Fields to fetch.
   */
  where?: Prisma.FieldWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Fields to fetch.
   */
  orderBy?: Prisma.FieldOrderByWithRelationInput | Prisma.FieldOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Fields.
   */
  cursor?: Prisma.FieldWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Fields from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Fields.
   */
  skip?: number
  distinct?: Prisma.FieldScalarFieldEnum | Prisma.FieldScalarFieldEnum[]
}

/**
 * Field create
 */
export type FieldCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Field
   */
  select?: Prisma.FieldSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Field
   */
  omit?: Prisma.FieldOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldInclude<ExtArgs> | null
  /**
   * The data needed to create a Field.
   */
  data: Prisma.XOR<Prisma.FieldCreateInput, Prisma.FieldUncheckedCreateInput>
}

/**
 * Field createMany
 */
export type FieldCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Fields.
   */
  data: Prisma.FieldCreateManyInput | Prisma.FieldCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Field update
 */
export type FieldUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Field
   */
  select?: Prisma.FieldSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Field
   */
  omit?: Prisma.FieldOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldInclude<ExtArgs> | null
  /**
   * The data needed to update a Field.
   */
  data: Prisma.XOR<Prisma.FieldUpdateInput, Prisma.FieldUncheckedUpdateInput>
  /**
   * Choose, which Field to update.
   */
  where: Prisma.FieldWhereUniqueInput
}

/**
 * Field updateMany
 */
export type FieldUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Fields.
   */
  data: Prisma.XOR<Prisma.FieldUpdateManyMutationInput, Prisma.FieldUncheckedUpdateManyInput>
  /**
   * Filter which Fields to update
   */
  where?: Prisma.FieldWhereInput
  /**
   * Limit how many Fields to update.
   */
  limit?: number
}

/**
 * Field upsert
 */
export type FieldUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Field
   */
  select?: Prisma.FieldSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Field
   */
  omit?: Prisma.FieldOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldInclude<ExtArgs> | null
  /**
   * The filter to search for the Field to update in case it exists.
   */
  where: Prisma.FieldWhereUniqueInput
  /**
   * In case the Field found by the `where` argument doesn't exist, create a new Field with this data.
   */
  create: Prisma.XOR<Prisma.FieldCreateInput, Prisma.FieldUncheckedCreateInput>
  /**
   * In case the Field was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FieldUpdateInput, Prisma.FieldUncheckedUpdateInput>
}

/**
 * Field delete
 */
export type FieldDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Field
   */
  select?: Prisma.FieldSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Field
   */
  omit?: Prisma.FieldOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldInclude<ExtArgs> | null
  /**
   * Filter which Field to delete.
   */
  where: Prisma.FieldWhereUniqueInput
}

/**
 * Field deleteMany
 */
export type FieldDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Fields to delete
   */
  where?: Prisma.FieldWhereInput
  /**
   * Limit how many Fields to delete.
   */
  limit?: number
}

/**
 * Field.options
 */
export type Field$optionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldOption
   */
  select?: Prisma.FieldOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FieldOption
   */
  omit?: Prisma.FieldOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldOptionInclude<ExtArgs> | null
  where?: Prisma.FieldOptionWhereInput
  orderBy?: Prisma.FieldOptionOrderByWithRelationInput | Prisma.FieldOptionOrderByWithRelationInput[]
  cursor?: Prisma.FieldOptionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FieldOptionScalarFieldEnum | Prisma.FieldOptionScalarFieldEnum[]
}

/**
 * Field.values
 */
export type Field$valuesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldValue
   */
  select?: Prisma.FieldValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FieldValue
   */
  omit?: Prisma.FieldValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldValueInclude<ExtArgs> | null
  where?: Prisma.FieldValueWhereInput
  orderBy?: Prisma.FieldValueOrderByWithRelationInput | Prisma.FieldValueOrderByWithRelationInput[]
  cursor?: Prisma.FieldValueWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FieldValueScalarFieldEnum | Prisma.FieldValueScalarFieldEnum[]
}

/**
 * Field without action
 */
export type FieldDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Field
   */
  select?: Prisma.FieldSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Field
   */
  omit?: Prisma.FieldOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldInclude<ExtArgs> | null
}
