
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FieldValue` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FieldValue
 * 
 */
export type FieldValueModel = runtime.Types.Result.DefaultSelection<Prisma.$FieldValuePayload>

export type AggregateFieldValue = {
  _count: FieldValueCountAggregateOutputType | null
  _min: FieldValueMinAggregateOutputType | null
  _max: FieldValueMaxAggregateOutputType | null
}

export type FieldValueMinAggregateOutputType = {
  id: string | null
  fieldId: string | null
  entityId: string | null
  value: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FieldValueMaxAggregateOutputType = {
  id: string | null
  fieldId: string | null
  entityId: string | null
  value: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FieldValueCountAggregateOutputType = {
  id: number
  fieldId: number
  entityId: number
  value: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type FieldValueMinAggregateInputType = {
  id?: true
  fieldId?: true
  entityId?: true
  value?: true
  createdAt?: true
  updatedAt?: true
}

export type FieldValueMaxAggregateInputType = {
  id?: true
  fieldId?: true
  entityId?: true
  value?: true
  createdAt?: true
  updatedAt?: true
}

export type FieldValueCountAggregateInputType = {
  id?: true
  fieldId?: true
  entityId?: true
  value?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type FieldValueAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FieldValue to aggregate.
   */
  where?: Prisma.FieldValueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FieldValues to fetch.
   */
  orderBy?: Prisma.FieldValueOrderByWithRelationInput | Prisma.FieldValueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FieldValueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FieldValues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FieldValues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FieldValues
  **/
  _count?: true | FieldValueCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FieldValueMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FieldValueMaxAggregateInputType
}

export type GetFieldValueAggregateType<T extends FieldValueAggregateArgs> = {
      [P in keyof T & keyof AggregateFieldValue]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFieldValue[P]>
    : Prisma.GetScalarType<T[P], AggregateFieldValue[P]>
}




export type FieldValueGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FieldValueWhereInput
  orderBy?: Prisma.FieldValueOrderByWithAggregationInput | Prisma.FieldValueOrderByWithAggregationInput[]
  by: Prisma.FieldValueScalarFieldEnum[] | Prisma.FieldValueScalarFieldEnum
  having?: Prisma.FieldValueScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FieldValueCountAggregateInputType | true
  _min?: FieldValueMinAggregateInputType
  _max?: FieldValueMaxAggregateInputType
}

export type FieldValueGroupByOutputType = {
  id: string
  fieldId: string
  entityId: string
  value: string
  createdAt: Date
  updatedAt: Date
  _count: FieldValueCountAggregateOutputType | null
  _min: FieldValueMinAggregateOutputType | null
  _max: FieldValueMaxAggregateOutputType | null
}

type GetFieldValueGroupByPayload<T extends FieldValueGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FieldValueGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FieldValueGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FieldValueGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FieldValueGroupByOutputType[P]>
      }
    >
  >



export type FieldValueWhereInput = {
  AND?: Prisma.FieldValueWhereInput | Prisma.FieldValueWhereInput[]
  OR?: Prisma.FieldValueWhereInput[]
  NOT?: Prisma.FieldValueWhereInput | Prisma.FieldValueWhereInput[]
  id?: Prisma.StringFilter<"FieldValue"> | string
  fieldId?: Prisma.StringFilter<"FieldValue"> | string
  entityId?: Prisma.StringFilter<"FieldValue"> | string
  value?: Prisma.StringFilter<"FieldValue"> | string
  createdAt?: Prisma.DateTimeFilter<"FieldValue"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FieldValue"> | Date | string
  field?: Prisma.XOR<Prisma.FieldScalarRelationFilter, Prisma.FieldWhereInput>
}

export type FieldValueOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  value?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  field?: Prisma.FieldOrderByWithRelationInput
  _relevance?: Prisma.FieldValueOrderByRelevanceInput
}

export type FieldValueWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  fieldId_entityId_value?: Prisma.FieldValueFieldIdEntityIdValueCompoundUniqueInput
  AND?: Prisma.FieldValueWhereInput | Prisma.FieldValueWhereInput[]
  OR?: Prisma.FieldValueWhereInput[]
  NOT?: Prisma.FieldValueWhereInput | Prisma.FieldValueWhereInput[]
  fieldId?: Prisma.StringFilter<"FieldValue"> | string
  entityId?: Prisma.StringFilter<"FieldValue"> | string
  value?: Prisma.StringFilter<"FieldValue"> | string
  createdAt?: Prisma.DateTimeFilter<"FieldValue"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FieldValue"> | Date | string
  field?: Prisma.XOR<Prisma.FieldScalarRelationFilter, Prisma.FieldWhereInput>
}, "id" | "fieldId_entityId_value">

export type FieldValueOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  value?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.FieldValueCountOrderByAggregateInput
  _max?: Prisma.FieldValueMaxOrderByAggregateInput
  _min?: Prisma.FieldValueMinOrderByAggregateInput
}

export type FieldValueScalarWhereWithAggregatesInput = {
  AND?: Prisma.FieldValueScalarWhereWithAggregatesInput | Prisma.FieldValueScalarWhereWithAggregatesInput[]
  OR?: Prisma.FieldValueScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FieldValueScalarWhereWithAggregatesInput | Prisma.FieldValueScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FieldValue"> | string
  fieldId?: Prisma.StringWithAggregatesFilter<"FieldValue"> | string
  entityId?: Prisma.StringWithAggregatesFilter<"FieldValue"> | string
  value?: Prisma.StringWithAggregatesFilter<"FieldValue"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"FieldValue"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"FieldValue"> | Date | string
}

export type FieldValueCreateInput = {
  id?: string
  entityId: string
  value: string
  createdAt?: Date | string
  updatedAt?: Date | string
  field: Prisma.FieldCreateNestedOneWithoutValuesInput
}

export type FieldValueUncheckedCreateInput = {
  id?: string
  fieldId: string
  entityId: string
  value: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FieldValueUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  field?: Prisma.FieldUpdateOneRequiredWithoutValuesNestedInput
}

export type FieldValueUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fieldId?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FieldValueCreateManyInput = {
  id?: string
  fieldId: string
  entityId: string
  value: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FieldValueUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FieldValueUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fieldId?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FieldValueListRelationFilter = {
  every?: Prisma.FieldValueWhereInput
  some?: Prisma.FieldValueWhereInput
  none?: Prisma.FieldValueWhereInput
}

export type FieldValueOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FieldValueOrderByRelevanceInput = {
  fields: Prisma.FieldValueOrderByRelevanceFieldEnum | Prisma.FieldValueOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type FieldValueFieldIdEntityIdValueCompoundUniqueInput = {
  fieldId: string
  entityId: string
  value: string
}

export type FieldValueCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  value?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FieldValueMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  value?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FieldValueMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fieldId?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  value?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FieldValueCreateNestedManyWithoutFieldInput = {
  create?: Prisma.XOR<Prisma.FieldValueCreateWithoutFieldInput, Prisma.FieldValueUncheckedCreateWithoutFieldInput> | Prisma.FieldValueCreateWithoutFieldInput[] | Prisma.FieldValueUncheckedCreateWithoutFieldInput[]
  connectOrCreate?: Prisma.FieldValueCreateOrConnectWithoutFieldInput | Prisma.FieldValueCreateOrConnectWithoutFieldInput[]
  createMany?: Prisma.FieldValueCreateManyFieldInputEnvelope
  connect?: Prisma.FieldValueWhereUniqueInput | Prisma.FieldValueWhereUniqueInput[]
}

export type FieldValueUncheckedCreateNestedManyWithoutFieldInput = {
  create?: Prisma.XOR<Prisma.FieldValueCreateWithoutFieldInput, Prisma.FieldValueUncheckedCreateWithoutFieldInput> | Prisma.FieldValueCreateWithoutFieldInput[] | Prisma.FieldValueUncheckedCreateWithoutFieldInput[]
  connectOrCreate?: Prisma.FieldValueCreateOrConnectWithoutFieldInput | Prisma.FieldValueCreateOrConnectWithoutFieldInput[]
  createMany?: Prisma.FieldValueCreateManyFieldInputEnvelope
  connect?: Prisma.FieldValueWhereUniqueInput | Prisma.FieldValueWhereUniqueInput[]
}

export type FieldValueUpdateManyWithoutFieldNestedInput = {
  create?: Prisma.XOR<Prisma.FieldValueCreateWithoutFieldInput, Prisma.FieldValueUncheckedCreateWithoutFieldInput> | Prisma.FieldValueCreateWithoutFieldInput[] | Prisma.FieldValueUncheckedCreateWithoutFieldInput[]
  connectOrCreate?: Prisma.FieldValueCreateOrConnectWithoutFieldInput | Prisma.FieldValueCreateOrConnectWithoutFieldInput[]
  upsert?: Prisma.FieldValueUpsertWithWhereUniqueWithoutFieldInput | Prisma.FieldValueUpsertWithWhereUniqueWithoutFieldInput[]
  createMany?: Prisma.FieldValueCreateManyFieldInputEnvelope
  set?: Prisma.FieldValueWhereUniqueInput | Prisma.FieldValueWhereUniqueInput[]
  disconnect?: Prisma.FieldValueWhereUniqueInput | Prisma.FieldValueWhereUniqueInput[]
  delete?: Prisma.FieldValueWhereUniqueInput | Prisma.FieldValueWhereUniqueInput[]
  connect?: Prisma.FieldValueWhereUniqueInput | Prisma.FieldValueWhereUniqueInput[]
  update?: Prisma.FieldValueUpdateWithWhereUniqueWithoutFieldInput | Prisma.FieldValueUpdateWithWhereUniqueWithoutFieldInput[]
  updateMany?: Prisma.FieldValueUpdateManyWithWhereWithoutFieldInput | Prisma.FieldValueUpdateManyWithWhereWithoutFieldInput[]
  deleteMany?: Prisma.FieldValueScalarWhereInput | Prisma.FieldValueScalarWhereInput[]
}

export type FieldValueUncheckedUpdateManyWithoutFieldNestedInput = {
  create?: Prisma.XOR<Prisma.FieldValueCreateWithoutFieldInput, Prisma.FieldValueUncheckedCreateWithoutFieldInput> | Prisma.FieldValueCreateWithoutFieldInput[] | Prisma.FieldValueUncheckedCreateWithoutFieldInput[]
  connectOrCreate?: Prisma.FieldValueCreateOrConnectWithoutFieldInput | Prisma.FieldValueCreateOrConnectWithoutFieldInput[]
  upsert?: Prisma.FieldValueUpsertWithWhereUniqueWithoutFieldInput | Prisma.FieldValueUpsertWithWhereUniqueWithoutFieldInput[]
  createMany?: Prisma.FieldValueCreateManyFieldInputEnvelope
  set?: Prisma.FieldValueWhereUniqueInput | Prisma.FieldValueWhereUniqueInput[]
  disconnect?: Prisma.FieldValueWhereUniqueInput | Prisma.FieldValueWhereUniqueInput[]
  delete?: Prisma.FieldValueWhereUniqueInput | Prisma.FieldValueWhereUniqueInput[]
  connect?: Prisma.FieldValueWhereUniqueInput | Prisma.FieldValueWhereUniqueInput[]
  update?: Prisma.FieldValueUpdateWithWhereUniqueWithoutFieldInput | Prisma.FieldValueUpdateWithWhereUniqueWithoutFieldInput[]
  updateMany?: Prisma.FieldValueUpdateManyWithWhereWithoutFieldInput | Prisma.FieldValueUpdateManyWithWhereWithoutFieldInput[]
  deleteMany?: Prisma.FieldValueScalarWhereInput | Prisma.FieldValueScalarWhereInput[]
}

export type FieldValueCreateWithoutFieldInput = {
  id?: string
  entityId: string
  value: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FieldValueUncheckedCreateWithoutFieldInput = {
  id?: string
  entityId: string
  value: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FieldValueCreateOrConnectWithoutFieldInput = {
  where: Prisma.FieldValueWhereUniqueInput
  create: Prisma.XOR<Prisma.FieldValueCreateWithoutFieldInput, Prisma.FieldValueUncheckedCreateWithoutFieldInput>
}

export type FieldValueCreateManyFieldInputEnvelope = {
  data: Prisma.FieldValueCreateManyFieldInput | Prisma.FieldValueCreateManyFieldInput[]
  skipDuplicates?: boolean
}

export type FieldValueUpsertWithWhereUniqueWithoutFieldInput = {
  where: Prisma.FieldValueWhereUniqueInput
  update: Prisma.XOR<Prisma.FieldValueUpdateWithoutFieldInput, Prisma.FieldValueUncheckedUpdateWithoutFieldInput>
  create: Prisma.XOR<Prisma.FieldValueCreateWithoutFieldInput, Prisma.FieldValueUncheckedCreateWithoutFieldInput>
}

export type FieldValueUpdateWithWhereUniqueWithoutFieldInput = {
  where: Prisma.FieldValueWhereUniqueInput
  data: Prisma.XOR<Prisma.FieldValueUpdateWithoutFieldInput, Prisma.FieldValueUncheckedUpdateWithoutFieldInput>
}

export type FieldValueUpdateManyWithWhereWithoutFieldInput = {
  where: Prisma.FieldValueScalarWhereInput
  data: Prisma.XOR<Prisma.FieldValueUpdateManyMutationInput, Prisma.FieldValueUncheckedUpdateManyWithoutFieldInput>
}

export type FieldValueScalarWhereInput = {
  AND?: Prisma.FieldValueScalarWhereInput | Prisma.FieldValueScalarWhereInput[]
  OR?: Prisma.FieldValueScalarWhereInput[]
  NOT?: Prisma.FieldValueScalarWhereInput | Prisma.FieldValueScalarWhereInput[]
  id?: Prisma.StringFilter<"FieldValue"> | string
  fieldId?: Prisma.StringFilter<"FieldValue"> | string
  entityId?: Prisma.StringFilter<"FieldValue"> | string
  value?: Prisma.StringFilter<"FieldValue"> | string
  createdAt?: Prisma.DateTimeFilter<"FieldValue"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FieldValue"> | Date | string
}

export type FieldValueCreateManyFieldInput = {
  id?: string
  entityId: string
  value: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FieldValueUpdateWithoutFieldInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FieldValueUncheckedUpdateWithoutFieldInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FieldValueUncheckedUpdateManyWithoutFieldInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type FieldValueSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fieldId?: boolean
  entityId?: boolean
  value?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  field?: boolean | Prisma.FieldDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fieldValue"]>



export type FieldValueSelectScalar = {
  id?: boolean
  fieldId?: boolean
  entityId?: boolean
  value?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type FieldValueOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "fieldId" | "entityId" | "value" | "createdAt" | "updatedAt", ExtArgs["result"]["fieldValue"]>
export type FieldValueInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  field?: boolean | Prisma.FieldDefaultArgs<ExtArgs>
}

export type $FieldValuePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FieldValue"
  objects: {
    field: Prisma.$FieldPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    fieldId: string
    entityId: string
    value: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["fieldValue"]>
  composites: {}
}

export type FieldValueGetPayload<S extends boolean | null | undefined | FieldValueDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FieldValuePayload, S>

export type FieldValueCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FieldValueFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FieldValueCountAggregateInputType | true
  }

export interface FieldValueDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FieldValue'], meta: { name: 'FieldValue' } }
  /**
   * Find zero or one FieldValue that matches the filter.
   * @param {FieldValueFindUniqueArgs} args - Arguments to find a FieldValue
   * @example
   * // Get one FieldValue
   * const fieldValue = await prisma.fieldValue.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FieldValueFindUniqueArgs>(args: Prisma.SelectSubset<T, FieldValueFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FieldValueClient<runtime.Types.Result.GetResult<Prisma.$FieldValuePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FieldValue that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FieldValueFindUniqueOrThrowArgs} args - Arguments to find a FieldValue
   * @example
   * // Get one FieldValue
   * const fieldValue = await prisma.fieldValue.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FieldValueFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FieldValueFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FieldValueClient<runtime.Types.Result.GetResult<Prisma.$FieldValuePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FieldValue that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldValueFindFirstArgs} args - Arguments to find a FieldValue
   * @example
   * // Get one FieldValue
   * const fieldValue = await prisma.fieldValue.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FieldValueFindFirstArgs>(args?: Prisma.SelectSubset<T, FieldValueFindFirstArgs<ExtArgs>>): Prisma.Prisma__FieldValueClient<runtime.Types.Result.GetResult<Prisma.$FieldValuePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FieldValue that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldValueFindFirstOrThrowArgs} args - Arguments to find a FieldValue
   * @example
   * // Get one FieldValue
   * const fieldValue = await prisma.fieldValue.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FieldValueFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FieldValueFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FieldValueClient<runtime.Types.Result.GetResult<Prisma.$FieldValuePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FieldValues that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldValueFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FieldValues
   * const fieldValues = await prisma.fieldValue.findMany()
   * 
   * // Get first 10 FieldValues
   * const fieldValues = await prisma.fieldValue.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const fieldValueWithIdOnly = await prisma.fieldValue.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FieldValueFindManyArgs>(args?: Prisma.SelectSubset<T, FieldValueFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FieldValuePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FieldValue.
   * @param {FieldValueCreateArgs} args - Arguments to create a FieldValue.
   * @example
   * // Create one FieldValue
   * const FieldValue = await prisma.fieldValue.create({
   *   data: {
   *     // ... data to create a FieldValue
   *   }
   * })
   * 
   */
  create<T extends FieldValueCreateArgs>(args: Prisma.SelectSubset<T, FieldValueCreateArgs<ExtArgs>>): Prisma.Prisma__FieldValueClient<runtime.Types.Result.GetResult<Prisma.$FieldValuePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FieldValues.
   * @param {FieldValueCreateManyArgs} args - Arguments to create many FieldValues.
   * @example
   * // Create many FieldValues
   * const fieldValue = await prisma.fieldValue.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FieldValueCreateManyArgs>(args?: Prisma.SelectSubset<T, FieldValueCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a FieldValue.
   * @param {FieldValueDeleteArgs} args - Arguments to delete one FieldValue.
   * @example
   * // Delete one FieldValue
   * const FieldValue = await prisma.fieldValue.delete({
   *   where: {
   *     // ... filter to delete one FieldValue
   *   }
   * })
   * 
   */
  delete<T extends FieldValueDeleteArgs>(args: Prisma.SelectSubset<T, FieldValueDeleteArgs<ExtArgs>>): Prisma.Prisma__FieldValueClient<runtime.Types.Result.GetResult<Prisma.$FieldValuePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FieldValue.
   * @param {FieldValueUpdateArgs} args - Arguments to update one FieldValue.
   * @example
   * // Update one FieldValue
   * const fieldValue = await prisma.fieldValue.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FieldValueUpdateArgs>(args: Prisma.SelectSubset<T, FieldValueUpdateArgs<ExtArgs>>): Prisma.Prisma__FieldValueClient<runtime.Types.Result.GetResult<Prisma.$FieldValuePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FieldValues.
   * @param {FieldValueDeleteManyArgs} args - Arguments to filter FieldValues to delete.
   * @example
   * // Delete a few FieldValues
   * const { count } = await prisma.fieldValue.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FieldValueDeleteManyArgs>(args?: Prisma.SelectSubset<T, FieldValueDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FieldValues.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldValueUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FieldValues
   * const fieldValue = await prisma.fieldValue.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FieldValueUpdateManyArgs>(args: Prisma.SelectSubset<T, FieldValueUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one FieldValue.
   * @param {FieldValueUpsertArgs} args - Arguments to update or create a FieldValue.
   * @example
   * // Update or create a FieldValue
   * const fieldValue = await prisma.fieldValue.upsert({
   *   create: {
   *     // ... data to create a FieldValue
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FieldValue we want to update
   *   }
   * })
   */
  upsert<T extends FieldValueUpsertArgs>(args: Prisma.SelectSubset<T, FieldValueUpsertArgs<ExtArgs>>): Prisma.Prisma__FieldValueClient<runtime.Types.Result.GetResult<Prisma.$FieldValuePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FieldValues.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldValueCountArgs} args - Arguments to filter FieldValues to count.
   * @example
   * // Count the number of FieldValues
   * const count = await prisma.fieldValue.count({
   *   where: {
   *     // ... the filter for the FieldValues we want to count
   *   }
   * })
  **/
  count<T extends FieldValueCountArgs>(
    args?: Prisma.Subset<T, FieldValueCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FieldValueCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FieldValue.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldValueAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FieldValueAggregateArgs>(args: Prisma.Subset<T, FieldValueAggregateArgs>): Prisma.PrismaPromise<GetFieldValueAggregateType<T>>

  /**
   * Group by FieldValue.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FieldValueGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FieldValueGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FieldValueGroupByArgs['orderBy'] }
      : { orderBy?: FieldValueGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FieldValueGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFieldValueGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FieldValue model
 */
readonly fields: FieldValueFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FieldValue.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FieldValueClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  field<T extends Prisma.FieldDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FieldDefaultArgs<ExtArgs>>): Prisma.Prisma__FieldClient<runtime.Types.Result.GetResult<Prisma.$FieldPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FieldValue model
 */
export interface FieldValueFieldRefs {
  readonly id: Prisma.FieldRef<"FieldValue", 'String'>
  readonly fieldId: Prisma.FieldRef<"FieldValue", 'String'>
  readonly entityId: Prisma.FieldRef<"FieldValue", 'String'>
  readonly value: Prisma.FieldRef<"FieldValue", 'String'>
  readonly createdAt: Prisma.FieldRef<"FieldValue", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"FieldValue", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FieldValue findUnique
 */
export type FieldValueFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldValue
   */
  select?: Prisma.FieldValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FieldValue
   */
  omit?: Prisma.FieldValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldValueInclude<ExtArgs> | null
  /**
   * Filter, which FieldValue to fetch.
   */
  where: Prisma.FieldValueWhereUniqueInput
}

/**
 * FieldValue findUniqueOrThrow
 */
export type FieldValueFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldValue
   */
  select?: Prisma.FieldValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FieldValue
   */
  omit?: Prisma.FieldValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldValueInclude<ExtArgs> | null
  /**
   * Filter, which FieldValue to fetch.
   */
  where: Prisma.FieldValueWhereUniqueInput
}

/**
 * FieldValue findFirst
 */
export type FieldValueFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldValue
   */
  select?: Prisma.FieldValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FieldValue
   */
  omit?: Prisma.FieldValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldValueInclude<ExtArgs> | null
  /**
   * Filter, which FieldValue to fetch.
   */
  where?: Prisma.FieldValueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FieldValues to fetch.
   */
  orderBy?: Prisma.FieldValueOrderByWithRelationInput | Prisma.FieldValueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FieldValues.
   */
  cursor?: Prisma.FieldValueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FieldValues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FieldValues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FieldValues.
   */
  distinct?: Prisma.FieldValueScalarFieldEnum | Prisma.FieldValueScalarFieldEnum[]
}

/**
 * FieldValue findFirstOrThrow
 */
export type FieldValueFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldValue
   */
  select?: Prisma.FieldValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FieldValue
   */
  omit?: Prisma.FieldValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldValueInclude<ExtArgs> | null
  /**
   * Filter, which FieldValue to fetch.
   */
  where?: Prisma.FieldValueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FieldValues to fetch.
   */
  orderBy?: Prisma.FieldValueOrderByWithRelationInput | Prisma.FieldValueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FieldValues.
   */
  cursor?: Prisma.FieldValueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FieldValues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FieldValues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FieldValues.
   */
  distinct?: Prisma.FieldValueScalarFieldEnum | Prisma.FieldValueScalarFieldEnum[]
}

/**
 * FieldValue findMany
 */
export type FieldValueFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldValue
   */
  select?: Prisma.FieldValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FieldValue
   */
  omit?: Prisma.FieldValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldValueInclude<ExtArgs> | null
  /**
   * Filter, which FieldValues to fetch.
   */
  where?: Prisma.FieldValueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FieldValues to fetch.
   */
  orderBy?: Prisma.FieldValueOrderByWithRelationInput | Prisma.FieldValueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FieldValues.
   */
  cursor?: Prisma.FieldValueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FieldValues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FieldValues.
   */
  skip?: number
  distinct?: Prisma.FieldValueScalarFieldEnum | Prisma.FieldValueScalarFieldEnum[]
}

/**
 * FieldValue create
 */
export type FieldValueCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldValue
   */
  select?: Prisma.FieldValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FieldValue
   */
  omit?: Prisma.FieldValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldValueInclude<ExtArgs> | null
  /**
   * The data needed to create a FieldValue.
   */
  data: Prisma.XOR<Prisma.FieldValueCreateInput, Prisma.FieldValueUncheckedCreateInput>
}

/**
 * FieldValue createMany
 */
export type FieldValueCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FieldValues.
   */
  data: Prisma.FieldValueCreateManyInput | Prisma.FieldValueCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FieldValue update
 */
export type FieldValueUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldValue
   */
  select?: Prisma.FieldValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FieldValue
   */
  omit?: Prisma.FieldValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldValueInclude<ExtArgs> | null
  /**
   * The data needed to update a FieldValue.
   */
  data: Prisma.XOR<Prisma.FieldValueUpdateInput, Prisma.FieldValueUncheckedUpdateInput>
  /**
   * Choose, which FieldValue to update.
   */
  where: Prisma.FieldValueWhereUniqueInput
}

/**
 * FieldValue updateMany
 */
export type FieldValueUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FieldValues.
   */
  data: Prisma.XOR<Prisma.FieldValueUpdateManyMutationInput, Prisma.FieldValueUncheckedUpdateManyInput>
  /**
   * Filter which FieldValues to update
   */
  where?: Prisma.FieldValueWhereInput
  /**
   * Limit how many FieldValues to update.
   */
  limit?: number
}

/**
 * FieldValue upsert
 */
export type FieldValueUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldValue
   */
  select?: Prisma.FieldValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FieldValue
   */
  omit?: Prisma.FieldValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldValueInclude<ExtArgs> | null
  /**
   * The filter to search for the FieldValue to update in case it exists.
   */
  where: Prisma.FieldValueWhereUniqueInput
  /**
   * In case the FieldValue found by the `where` argument doesn't exist, create a new FieldValue with this data.
   */
  create: Prisma.XOR<Prisma.FieldValueCreateInput, Prisma.FieldValueUncheckedCreateInput>
  /**
   * In case the FieldValue was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FieldValueUpdateInput, Prisma.FieldValueUncheckedUpdateInput>
}

/**
 * FieldValue delete
 */
export type FieldValueDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldValue
   */
  select?: Prisma.FieldValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FieldValue
   */
  omit?: Prisma.FieldValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldValueInclude<ExtArgs> | null
  /**
   * Filter which FieldValue to delete.
   */
  where: Prisma.FieldValueWhereUniqueInput
}

/**
 * FieldValue deleteMany
 */
export type FieldValueDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FieldValues to delete
   */
  where?: Prisma.FieldValueWhereInput
  /**
   * Limit how many FieldValues to delete.
   */
  limit?: number
}

/**
 * FieldValue without action
 */
export type FieldValueDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FieldValue
   */
  select?: Prisma.FieldValueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FieldValue
   */
  omit?: Prisma.FieldValueOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FieldValueInclude<ExtArgs> | null
}
